name: Contract tests

on:
  schedule:
    - cron: '31 6 * * *'
  workflow_dispatch:
  workflow_call:

jobs:
  contract-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contract-tests
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version: '1.27'

      - run: go test ./...
